# path to dataset, need modification if necessary
DATASET:
  PATH: ../train-data/
  VERSION: DatasetV3

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/
    # period: 10
    MONITOR: train_loss
    FILENAME: "{experiment}-{{epoch}}--{{train_loss:.5f}}"
    save_top_k: 1

LOSS:
  VERSION: ReduceLoss

MODEL:
  VERSION: keypointrcnn
  REPLACE_RELU: true
  HEAD_PARAMS: null

METRIC:
  VERSION: mAP
  ARGS:
    threshold: 0.75

LIGHTING:
  VERSION: LightingModuleV2

TRAINER:
  MAX_EPOCHS: 200
  GPUS: 1
  #ACCELERATOR: ddp
  #SYNC_BATCHNORM: true
  NUM_NODES: 1
  #MAX_STEPS: 500
  gradient_clip_val: 0.5

OPTIMIZER:
  ARGS:
    LR: 0.00001
  SCHEDULER:
    USE: false

DATALOADER:
  BATCH_SIZE:
    TRAIN: 8
    TEST: 8
    VAL: 8
  COLLATE_FN: object_detection_collate
  VERSION: DataLoaderV2

SEED: 1024
