# path to dataset, need modification if necessary
DATASET:
  PATH: ../train-data/

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/

#LOSS:
#  ARGS:
#    ALPHA: 0.75

MODEL:
  VERSION: FPN
  REPLACE_RELU: false
  ENCODER: resnet18
  HEAD_PARAMS:
    in_features: 256
    output_shape: [50, 3]
    kernel_size: [3, 32]
    padding: [1, 0]


TRAINER:
  MAX_EPOCHS: 200
  GPUS: 1
  #ACCELERATOR: ddp
  #SYNC_BATCHNORM: true
  NUM_NODES: 1
  #MAX_STEPS: 500

OPTIMIZER:
  ARGS:
    LR: 0.01
  SCHEDULER:
    USE: false

DATALOADER:
  BATCH_SIZE:
    TRAIN: 8
    TEST: 8
    VAL: 8

SEED: 2021
