# path to dataset, need modification if necessary
DATASET:
  PATH: ../train-data-v7/train-data/
  LABEL_SHAPE: [128, 128]
  IMAGE_SHAPE: [128, 128]
  VERSION: DatasetV8
  SMOOTH: 3

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/
    save_last: true

LOSS:
  VERSION: JaccardLoss
  ARGS:
    mode: binary

MODEL:
  VERSION: FPNV4
  REPLACE_RELU: true
  ENCODER: efficientnet-b0
  HEAD_PARAMS: null


TRANSFORM:
  VERSION: TransformV2


TRAINER:
  MAX_EPOCHS: 500
  GPUS: 1
  #ACCELERATOR: ddp
  #SYNC_BATCHNORM: true
  NUM_NODES: 1
  #MAX_STEPS: 20000
  check_val_every_n_epoch: 500
  gradient_clip_val: 0.5

OPTIMIZER:
  ARGS:
    LR: 0.0001
  SCHEDULER:
    USE: false
    # VERSION: linear_schedule_with_warmup

DATALOADER:
  BATCH_SIZE:
    TRAIN: 32
    TEST: 32
    VAL: 32
  VERSION: DataLoaderV2
  
SEED: 1024
