# path to dataset, need modification if necessary
DATASET:
  PATH: ../train-data-rough/
  LABEL_SHAPE: [256, 3]
  VERSION: DatasetV2
  SMOOTH: 3

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/
    save_last: true

LOSS:
  VERSION: BCE

MODEL:
  VERSION: FPNV2
  REPLACE_RELU: true
  ENCODER: efficientnet-b0
  HEAD_PARAMS: null
  IN_CHANNELS: 1

TRANSFORM:
  VERSION: TransformV4

TRAINER:
  #MAX_EPOCHS: 1000
  GPUS: 1
  #ACCELERATOR: ddp
  #SYNC_BATCHNORM: true
  NUM_NODES: 1
  MAX_STEPS: 2000
  gradient_clip_val: 0.5

OPTIMIZER:
  ARGS:
    LR: 0.00001
  SCHEDULER:
    USE: false

DATALOADER:
  BATCH_SIZE:
    TRAIN: 16
    TEST: 16
    VAL: 16
  VERSION: DataLoaderV2
  
SEED: 1024
